In [13]:
import numpy as np

NumPy的数组类是ndarray，它有一个别名是 numpy.array，但这与Python标准库的array.array并不一样。后者仅仅是一个一维数组。而ndarray具有以下的属性：

ndarray.ndim：数组的维数。在Python世界中，维数称之为rank
ndarray.shape：数组的维度。这是一系列数字，长度由数组的维度（ndim）决定。例如：长度为n的一维数组的shape是(n)。一个n行m列的矩阵的shape是(n,m)
ndarray.size：数组中所有元素的数量
ndarray.dtype：数组中元素的类型，例如numpy.int32, numpy.int16或者numpy.float64
ndarray.itemsize：数组中每个元素的大小，单位为字节
ndarray.data：存储数组元素的缓冲。通常我们只需要通过下标来访问元素，而不需要访问缓冲

In [5]:
a=np.array([1,2,3])
b=np.array([(1,2,3),(4,5,6)])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [6]:
print("a's ndim {}".format(b.ndim))
print("a's share {}".format(b.shape))
print("a's size {}".format(b.size))
print("a's dtype {}".format(b.dtype))
print("a's itemsize {}".format(b.itemsize))

a's ndim 2
a's share (2, 3)
a's size 6
a's dtype int32
a's itemsize 4


In [16]:
print('np.zeros',np.zeros((2,3)))
print('np.ones',np.ones((3,4)))
print('np.empty',np.empty((3,4)))
print('np.arange',np.arange(1,4))
print('np.linspace',np.linspace(1,4,20))
print('np.random.random',np.random.random((2,3)))

np.zeros [[0. 0. 0.]
 [0. 0. 0.]]
np.ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
np.empty [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
np.arange [1 2 3]
np.linspace [1.         1.15789474 1.31578947 1.47368421 1.63157895 1.78947368
 1.94736842 2.10526316 2.26315789 2.42105263 2.57894737 2.73684211
 2.89473684 3.05263158 3.21052632 3.36842105 3.52631579 3.68421053
 3.84210526 4.        ]
np.random.random [[0.36527269 0.34463593 0.73668106]
 [0.34360103 0.86645748 0.72572932]]


In [29]:
zero_line=np.zeros((1,3))
print('zero_line is {}'.format(zero_line))
one_column=np.ones((3,1))
print('one_column is {}'.format(one_column))
a=np.array([(1,2,3),(4,5,6)])
b=np.arange(11,20)
print('a is {}'.format(a))
print('b is {}'.format(b))
print(zero_line.ndim,a.ndim,b.ndim)
b=b.reshape(3,-1)
print('b.reshape(3,-1) is {}'.format(b))
# vstack 保持列数一致
c=np.vstack((zero_line,a,b))
print('c is {}'.format(c))
# hstack 保持行数一致
a=a.reshape(3,2)
d=np.hstack((a,b,one_column))
print('d is {}'.format(d))

zero_line is [[0. 0. 0.]]
one_column is [[1.]
 [1.]
 [1.]]
a is [[1 2 3]
 [4 5 6]]
b is [11 12 13 14 15 16 17 18 19]
2 2 1
b.reshape(3,-1) is [[11 12 13]
 [14 15 16]
 [17 18 19]]
c is [[ 0.  0.  0.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]
d is [[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]


In [33]:
e=np.hsplit(d,3)
print(e)
#f=np.hsplit(d,4)
#print(f)

ValueError: array split does not result in an equal division

In [35]:
g=np.vsplit(d,3)
print(g)

[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]


In [45]:
import numpy as np
base_data=np.arange(100,200)
print('base_data is {}'.format(base_data))
every_five=np.arange(0,100,5)
print('base_data in five index {}'.format(base_data[every_five]))
a=np.array([(1,2),(10,20)])
print('base_data in array {}'.format(base_data[a]))
base_data=base_data.reshape((10,-1))
print('base_data is {}'.format(base_data))
print('access base_data ',base_data[2],base_data[2,3],base_data[-1,-1])
print('base_data[2,:] is {}'.format(base_data[2,:]))
print('base_data[:,3] is {}'.format(base_data[:,3]))
print('base_data[2:5,3:5] is {}'.format(base_data[2:5,3:5]))

base_data is [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
base_data in five index [100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]
base_data in array [[101 102]
 [110 120]]
base_data is [[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 1

In [48]:
import numpy as np
base_data=(np.random.random((5,5))-0.5)*100
print('base_data is {}'.format(base_data))
print('np.amin(base_data) is {}'.format(np.amin(base_data)))
print('np.amax(base_data) is {}'.format(np.amax(base_data)))
print('np.average(base_data) is {}'.format(np.average(base_data)))
print('np.sum(base_data) is {}'.format(np.sum(base_data)))
print('np.sin(base_data) is {}'.format(np.sin(base_data)))


base_data is [[-30.56811268  21.85090306 -14.12926569 -17.44078125   8.54818383]
 [-45.07914778   9.04126277 -48.51152272  -4.20347391  39.02095991]
 [ 18.2118767  -42.29759621  -0.62797765  21.90497154 -22.65531617]
 [ 31.75266007 -15.35712318  36.46343797 -30.72057514  16.49600579]
 [ 34.28033712  17.69832221 -21.32255896  32.80703491  18.64483734]]
np.amin(base_data) is -48.511522717791
np.amax(base_data) is 39.02095990743025
np.average(base_data) is 0.5522936757837216
np.sum(base_data) is 13.80734189459304
np.sin(base_data) is [[ 0.7498358   0.13978622 -0.99996879  0.98690318  0.76856436]
 [-0.8897744   0.3741826   0.98327243  0.87327363  0.96917209]
 [-0.59533235  0.99351988 -0.58750944  0.08607041  0.61640388]
 [ 0.33040585 -0.34368684 -0.94437004  0.64065529 -0.70897415]
 [ 0.27364637 -0.9132672  -0.61987988  0.98389951 -0.20329163]]


In [60]:
import numpy as np
base_data=np.floor((np.random.random((5,5))-0.5)*100)
print('base_data is {}'.format(base_data))
print('base_data.T is {}'.format(base_data.T))
print('base_data.transpose() is {}'.format(base_data.transpose()))
matrix_one=np.ones((5,5))
print('matrix_one is {}'.format(matrix_one))
minus_one=np.dot(matrix_one,-1)
print('base_data is {}'.format(base_data))
print('minus_one is {}'.format(minus_one))
# 矩阵相乘等于 m行与n列对应位置上所有元素相乘再相加和
print('base_data*minus_one is {}'.format(np.dot(base_data,minus_one)))


base_data is [[-31.  -2.  31.  45.  40.]
 [ 28. -47.  45.  29.  26.]
 [ -9. -44.  28. -10. -45.]
 [-25. -27. -13.   5. -12.]
 [-16.  -7.  21. -13. -46.]]
base_data.T is [[-31.  28.  -9. -25. -16.]
 [ -2. -47. -44. -27.  -7.]
 [ 31.  45.  28. -13.  21.]
 [ 45.  29. -10.   5. -13.]
 [ 40.  26. -45. -12. -46.]]
base_data.transpose() is [[-31.  28.  -9. -25. -16.]
 [ -2. -47. -44. -27.  -7.]
 [ 31.  45.  28. -13.  21.]
 [ 45.  29. -10.   5. -13.]
 [ 40.  26. -45. -12. -46.]]
matrix_one is [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
base_data is [[-31.  -2.  31.  45.  40.]
 [ 28. -47.  45.  29.  26.]
 [ -9. -44.  28. -10. -45.]
 [-25. -27. -13.   5. -12.]
 [-16.  -7.  21. -13. -46.]]
minus_one is [[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]
base_data*minus_one is [[-83. -83. -83. -83. -83.]
 [-81. -81. -81. -81. -81.]
 [ 80.  80.  80.  80.  80.]
 [ 72.  72.  72.  72.  72.]
 

In [64]:
import numpy as np
print('random:{}'.format(np.random.random(20)))
print('random:{}'.format(np.random.random((3,4))))
print('randint:{}'.format(np.random.randint(0,100,20)))
print('np.random.permutation:{}'.format(np.random.permutation(np.arange(20))))

random:[0.00675045 0.44775276 0.19905813 0.11184593 0.55069153 0.55767746
 0.38170719 0.32889903 0.14526909 0.63582142 0.34101588 0.12011544
 0.76646781 0.28610448 0.41939623 0.18351233 0.67498127 0.02135089
 0.93519104 0.6871007 ]
random:[[0.39315711 0.32110438 0.57408611 0.10133076]
 [0.59591205 0.86388437 0.57903825 0.92276517]
 [0.0675214  0.09284112 0.92927683 0.07833302]]
randint:[71 57 88 62 97 87 28 33 97 43 24 24 86 31 35 59 42 42 92 39]
np.random.permutation:[13  3 18  2  7 17 12 15  8  5 11  6  0 19  9 10  1  4 14 16]
