In [3]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

print(tf.__version__)

b'Hello, TensorFlow!'
1.6.0


In [4]:
def estimate_house_sales_price(num_of_bedrooms, sqft, neighborhood):
    price = 0

    # 加少量配方1
    price += num_of_bedrooms * 0.123

    # 加大把配方2
    price += sqft * 0.41

    # 适量的配方3
    price += neighborhood * 0.57

    return price

In [ ]:
print(estimate_house_sales_price(3,2000,3))

822.0790000000001


In [5]:
import tensorflow as tf
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=1)]
# Set up a linear classifier.
classifier = tf.estimator.LinearClassifier(feature_columns=feature_columns)

# Train the model on some example data.
classifier.train(input_fn=train_input_fn, steps=2000)

# Use it to predict.
predictions = classifier.predict(input_fn=predict_input_fn)

INFO:tensorflow:Using default config.


INFO:tensorflow:Using config: {'_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_service': None, '_save_checkpoints_secs': 600, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000000C4B99E8>, '_save_summary_steps': 100, '_evaluation_master': '', '_model_dir': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp7idaedc5', '_session_config': None, '_task_id': 0, '_global_id_in_cluster': 0, '_is_chief': True, '_task_type': 'worker', '_num_worker_replicas': 1, '_log_step_count_steps': 100, '_tf_random_seed': None, '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_num_ps_replicas': 0}


NameError: name 'train_input_fn' is not defined

In [6]:
import tensorflow as tf
# NumPy is often used to load, manipulate and preprocess data.
import numpy as np

# Declare list of features. We only have one numeric feature. There are many
# other types of columns that are more complicated and useful.
feature_columns = [tf.feature_column.numeric_column("x", shape=[1])]

# An estimator is the front end to invoke training (fitting) and evaluation
# (inference). There are many predefined types like linear regression,
# linear classification, and many neural network classifiers and regressors.
# The following code provides an estimator that does linear regression.
estimator = tf.estimator.LinearRegressor(feature_columns=feature_columns)

# TensorFlow provides many helper methods to read and set up data sets.
# Here we use two data sets: one for training and one for evaluation
# We have to tell the function how many batches
# of data (num_epochs) we want and how big each batch should be.
x_train = np.array([1., 2., 3., 4.])
y_train = np.array([0., -1., -2., -3.])
x_eval = np.array([2., 5., 8., 1.])
y_eval = np.array([-1.01, -4.1, -7, 0.])
input_fn = tf.estimator.inputs.numpy_input_fn(
    {"x": x_train}, y_train, batch_size=4, num_epochs=None, shuffle=True)
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    {"x": x_train}, y_train, batch_size=4, num_epochs=1000, shuffle=False)
eval_input_fn = tf.estimator.inputs.numpy_input_fn(
    {"x": x_eval}, y_eval, batch_size=4, num_epochs=1000, shuffle=False)

# We can invoke 1000 training steps by invoking the  method and passing the
# training data set.
estimator.train(input_fn=input_fn, steps=1000)

# Here we evaluate how well our model did.
train_metrics = estimator.evaluate(input_fn=train_input_fn)
eval_metrics = estimator.evaluate(input_fn=eval_input_fn)
print("train metrics: %r"% train_metrics)

INFO:tensorflow:Using default config.


INFO:tensorflow:Using config: {'_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_service': None, '_save_checkpoints_secs': 600, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000000C539F60>, '_save_summary_steps': 100, '_evaluation_master': '', '_model_dir': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp56ts3i_0', '_session_config': None, '_task_id': 0, '_global_id_in_cluster': 0, '_is_chief': True, '_task_type': 'worker', '_num_worker_replicas': 1, '_log_step_count_steps': 100, '_tf_random_seed': None, '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_num_ps_replicas': 0}


INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Create CheckpointSaverHook.


INFO:tensorflow:Graph was finalized.


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Saving checkpoints for 1 into C:\Users\ADMINI~1\AppData\Local\Temp\tmp56ts3i_0\model.ckpt.


INFO:tensorflow:loss = 3.0, step = 1


INFO:tensorflow:global_step/sec: 1068.38


INFO:tensorflow:loss = 0.20474115, step = 101 (0.078 sec)


INFO:tensorflow:global_step/sec: 1068.38


INFO:tensorflow:loss = 0.0222008, step = 201 (0.094 sec)


INFO:tensorflow:global_step/sec: 1282.05


INFO:tensorflow:loss = 0.011723988, step = 301 (0.078 sec)


INFO:tensorflow:global_step/sec: 801.281


INFO:tensorflow:loss = 0.00079590833, step = 401 (0.125 sec)


INFO:tensorflow:global_step/sec: 1068.38


INFO:tensorflow:loss = 0.00032431333, step = 501 (0.094 sec)


INFO:tensorflow:global_step/sec: 1282.05


INFO:tensorflow:loss = 5.137001e-05, step = 601 (0.078 sec)


INFO:tensorflow:global_step/sec: 1282.05


INFO:tensorflow:loss = 3.7776335e-06, step = 701 (0.078 sec)


INFO:tensorflow:global_step/sec: 1282.05


INFO:tensorflow:loss = 2.3318853e-06, step = 801 (0.078 sec)


INFO:tensorflow:global_step/sec: 1057.08


INFO:tensorflow:loss = 6.34922e-07, step = 901 (0.096 sec)


INFO:tensorflow:Saving checkpoints for 1000 into C:\Users\ADMINI~1\AppData\Local\Temp\tmp56ts3i_0\model.ckpt.


INFO:tensorflow:Loss for final step: 9.721404e-08.


INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Starting evaluation at 2018-03-27-01:44:42


INFO:tensorflow:Graph was finalized.

INFO:tensorflow:Restoring parameters from C:\Users\ADMINI~1\AppData\Local\Temp\tmp56ts3i_0\model.ckpt-1000


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Finished evaluation at 2018-03-27-01:44:43


INFO:tensorflow:Saving dict for global step 1000: average_loss = 1.9100519e-08, global_step = 1000, loss = 7.6402074e-08


INFO:tensorflow:Calling model_fn.


INFO:tensorflow:Done calling model_fn.


INFO:tensorflow:Starting evaluation at 2018-03-27-01:44:43


INFO:tensorflow:Graph was finalized.


INFO:tensorflow:Restoring parameters from C:\Users\ADMINI~1\AppData\Local\Temp\tmp56ts3i_0\model.ckpt-1000


INFO:tensorflow:Running local_init_op.


INFO:tensorflow:Done running local_init_op.


INFO:tensorflow:Finished evaluation at 2018-03-27-01:44:43


INFO:tensorflow:Saving dict for global step 1000: average_loss = 0.0025351061, global_step = 1000, loss = 0.010140425


train metrics: {'average_loss': 1.9100519e-08, 'loss': 7.6402074e-08, 'global_step': 1000}


In [2]:
# 张量(####标量(零阶张量) 矢量(一阶张量) 矩阵(二阶张量)####) 指令 图
import tensorflow as tf
# create graph
g=tf.Graph()
# 设置为默认图
with g.as_default():
    # 创建常量
    x=tf.constant(8,name='x_const')
    y=tf.constant(5,name='y_const')
    z=tf.constant(4,name='z_const')
    sum=tf.add(x,y,name='x_y_sum')
    sum=tf.add(z,sum,name='x_y_z_sum')
    # 创建session
    with tf.Session() as sess:
        print(sum.eval())

17


In [5]:
import tensorflow as tf
c = tf.constant('Hello, world!')
with tf.Session() as sess:
    print(sess.run(c))

b'Hello, world!'


In [7]:
import tensorflow as tf
with tf.Graph().as_default():
    primes=tf.constant([2,3,5,7,9,11],dtype=tf.int32)
    ones=tf.ones([6],dtype=tf.int32)
    # 矢量相加
    beyond_primes=tf.add(primes,ones)
    # 创建Session 运行默认图
    with tf.Session() as sess:
        print(beyond_primes.eval())

[ 3  4  6  8 10 12]


In [8]:
import tensorflow as tf
with tf.Graph().as_default():
    # A scalar (0-D tensor).
    scalar = tf.zeros([])
    # A vector with 3 elements.
    vector = tf.zeros([3])
    # A matrix with 2 rows and 3 columns.
    matrix = tf.zeros([2, 3])
    with tf.Session() as sess:
        print('scalar has shape', scalar.get_shape(), 'and value:\n', scalar.eval())
        print('vector has shape', vector.get_shape(), 'and value:\n', vector.eval())
        print('matrix has shape', matrix.get_shape(), 'and value:\n', matrix.eval())

scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [0. 0. 0.]
matrix has shape (2, 3) and value:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
with tf.Graph().as_default():
    # Create a six-element vector (1-D tensor).
    primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
    # Create a constant scalar with value 1.
    ones = tf.constant(1, dtype=tf.int32)
    # Add the two tensors. The resulting tensor is a six-element vector.
    just_beyond_primes = tf.add(primes, ones)

    with tf.Session() as sess:
        print(just_beyond_primes.eval())

[ 3  4  6  8 12 14]


In [10]:
import tensorflow as tf
with tf.Graph().as_default():
    # Create a matrix (2-d tensor) with 3 rows and 4 columns.
    x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
                    dtype=tf.int32)
    # Create a matrix with 4 rows and 2 columns.
    y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)
    # Multiply `x` by `y`. 
    # The resulting matrix will have 3 rows and 2 columns.
    matrix_multiply_result = tf.matmul(x, y)
    with tf.Session() as sess:
        print(matrix_multiply_result.eval())

[[35 58]
 [35 33]
 [ 1 -4]]


In [11]:
with tf.Graph().as_default():
    # Create an 8x2 matrix (2-D tensor).
    matrix = tf.constant([[1,2], [3,4], [5,6], [7,8],
                          [9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)
    # Reshape the 8x2 matrix into a 2x8 matrix.
    reshaped_2x8_matrix = tf.reshape(matrix, [2,8])
    # Reshape the 8x2 matrix into a 4x4 matrix
    reshaped_4x4_matrix = tf.reshape(matrix, [4,4])
    with tf.Session() as sess:
        print("Original matrix (8x2):")
        print(matrix.eval())
        print("Reshaped matrix (2x8):")
        print(reshaped_2x8_matrix.eval())
        print("Reshaped matrix (4x4):")
        print(reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
with tf.Graph().as_default():
    # Create an 8x2 matrix (2-D tensor).
    matrix = tf.constant([[1,2], [3,4], [5,6], [7,8],
                          [9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)
    # Reshape the 8x2 matrix into a 3-D 2x2x4 tensor.
    reshaped_2x2x4_tensor = tf.reshape(matrix, [2,2,4])
    # Reshape the 8x2 matrix into a 1-D 16-element tensor.
    one_dimensional_vector = tf.reshape(matrix, [16])
    with tf.Session() as sess:
        print("Original matrix (8x2):")
        print(matrix.eval())
        print("Reshaped 3-D tensor (2x2x4):")
        print(reshaped_2x2x4_tensor.eval())
        print("1-D vector:")
        print(one_dimensional_vector.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped 3-D tensor (2x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
1-D vector:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [15]:
import tensorflow as tf
with tf.Graph().as_default():
    a = tf.constant([5, 3, 2, 7, 1, 4])
    b = tf.constant([4, 6, 3])
    c=tf.reshape(a,[2,3])
    d=tf.reshape(b,[3,1])
    matrix_multiply_result = tf.matmul(c, d)
    with tf.Session() as sess:
        print(matrix_multiply_result.eval())

[[44]
 [46]]


In [16]:
import tensorflow as tf
with tf.Graph().as_default():
    a=tf.Variable([3])
    v=tf.Variable(tf.random_normal([1],mean=1.0,stddev=0.32))

In [18]:
import tensorflow as tf
with g.as_default():
    v = tf.Variable([3])
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        # This should print the variable's initial value.
        print(v.eval())
        assignment = tf.assign(v, [7])
        # The variable has not been changed yet!
        print(v.eval())
        # Execute the assignment op.
        sess.run(assignment)
        # Now the variable is updated.
        print(v.eval())

[3]
[3]
[7]


In [19]:
import tensorflow as tf
with tf.Graph().as_default(), tf.Session() as sess:
    # Task 2: Simulate 10 throws of two dice. Store the results
    # in a 10x3 matrix.

    # We're going to place dice throws inside two separate
    # 10x1 matrices. We could have placed dice throws inside
    # a single 10x2 matrix, but adding different columns of
    # the same matrix is tricky. We also could have placed
    # dice throws inside two 1-D tensors (vectors); doing so
    # would require transposing the result.
    dice1 = tf.Variable(tf.random_uniform([10, 1],
                                          minval=1, maxval=7,
                                          dtype=tf.int32))
    dice2 = tf.Variable(tf.random_uniform([10, 1],
                                          minval=1, maxval=7,
                                          dtype=tf.int32))
    # We may add dice1 and dice2 since they share the same shape
    # and size.
    dice_sum = tf.add(dice1, dice2)
    # We've got three separate 10x1 matrices. To produce a single
    # 10x3 matrix, we'll concatenate them along dimension 1.
    resulting_matrix = tf.concat(
        values=[dice1, dice2, dice_sum], axis=1)
    # The variables haven't been initialized within the graph yet,
    # so let's remedy that.
    sess.run(tf.global_variables_initializer())
    print(resulting_matrix.eval())

[[ 4  1  5]
 [ 2  1  3]
 [ 5  6 11]
 [ 6  4 10]
 [ 6  5 11]
 [ 1  4  5]
 [ 4  6 10]
 [ 5  2  7]
 [ 1  5  6]
 [ 5  3  8]]
