In [1]:
import numpy as np
# 创建数组
x=np.array(5)
print(x)

5


In [2]:
x=np.array([1,2,3,4])
print(x)
print(x.ndim)

[1 2 3 4]
1


In [3]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
x = np.array([[[5,10,15,30,25],
               [20,30,65,70,90],
               [7,80,95,20,30]],

              [[3,0,5,0,45],
               [12,-2,6,7,90],
               [18,-9,95,120,30]],

              [[17,13,25,30,15],
               [23,36,9,7,80],
               [1,-7,-5,22,3]]])

print(x)
print(x.ndim)

[[[  5  10  15  30  25]
  [ 20  30  65  70  90]
  [  7  80  95  20  30]]

 [[  3   0   5   0  45]
  [ 12  -2   6   7  90]
  [ 18  -9  95 120  30]]

 [[ 17  13  25  30  15]
  [ 23  36   9   7  80]
  [  1  -7  -5  22   3]]]
3


In [3]:
import collections
count = [['UNK', -1]]
vocabulary_size=5
words=['萧炎','灵魂','火焰','萧薰儿','药老','天阶',"云岚宗","乌坦城","惊诧",'药老','天阶',"云岚宗"]
count.extend(collections.Counter(words).most_common(vocabulary_size - 1))
for word, _ in count:
    print(word+'\t',_)

UNK	 -1
天阶	 2
药老	 2
云岚宗	 2
乌坦城	 1
